 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author stell
 */
public class FenetreQuiz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());

    Question[] questions;
    int index = 0;
    int score = 0;
    
    public FenetreQuiz() {
        initComponents();
        questions = new Question[5];
        
        questions[0] = new Question (" Capitale de la France ?", "Paris", "Lyon","Nice","Lille",1);
        questions[1] = new Question ("2+2 ?", "3", "4", "5", "6",2);
        questions[2] = new Question("Animal qui aboie ?", "Chat","Vache", "Chien", "Lapin", 3);
        questions[3] = new Question("Couleur du ciel ?", "Vert", "Bleu","Rouge","Jaune",2);
        questions[4] = new Question("Soleil = ?", "Etoile", "Planete", "Pierre", "Nuage", 1);
            
        afficherQuestion();
    }
    
     
private void repondre (int choix) {
    Question q = questions[index];
    
    if (choix == q.getIndexBonneReponse()) {
        lbl_Feedback.setText("Bonne reponse !");
        score++;
    }else {
        lbl_Feedback.setText("Mauvaise reponse...");
    }
    
    lblScore.setText("Score : " + score);
    
    btnRep1.setEnabled(false);
    btnRep2.setEnabled(false);
    btnRep3.setEnabled(false);
    btnRep4.setEnabled(false);
    }
        
private void afficherQuestion() {
    Question q = questions[index];
    lblQuestion.setText(q.getIntitule());
    btnRep1.setText(q.getProposition1());
    btnRep2.setText(q.getProposition2());
    btnRep3.setText(q.getProposition3());
    btnRep4.setText(q.getProposition4());

    lbl_Feedback.setText("");
    
    btnRep1.setEnabled(true);
    btnRep2.setEnabled(true);
    btnRep3.setEnabled(true);
    btnRep4.setEnabled(true);
    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuestion = new javax.swing.JLabel();
        btnRep1 = new javax.swing.JButton();
        btnRep2 = new javax.swing.JButton();
        btnRep3 = new javax.swing.JButton();
        btnRep4 = new javax.swing.JButton();
        lbl_Feedback = new javax.swing.JLabel();
        btnSuivante = new javax.swing.JButton();
        lblScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblQuestion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblQuestion.setForeground(new java.awt.Color(255, 51, 153));
        lblQuestion.setText("Question :");

        btnRep1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRep1.setForeground(new java.awt.Color(255, 102, 102));
        btnRep1.setText("btnRep1");
        btnRep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep1ActionPerformed(evt);
            }
        });

        btnRep2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRep2.setForeground(new java.awt.Color(255, 102, 102));
        btnRep2.setText("btnRep4");
        btnRep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep2ActionPerformed(evt);
            }
        });

        btnRep3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRep3.setForeground(new java.awt.Color(255, 102, 102));
        btnRep3.setText("btnRep3");
        btnRep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep3ActionPerformed(evt);
            }
        });

        btnRep4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRep4.setForeground(new java.awt.Color(255, 102, 102));
        btnRep4.setText("btnRep4");
        btnRep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep4ActionPerformed(evt);
            }
        });

        lbl_Feedback.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        lbl_Feedback.setForeground(new java.awt.Color(255, 51, 51));
        lbl_Feedback.setText("Feedback :");

        btnSuivante.setText("Question suivante : ");
        btnSuivante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivanteActionPerformed(evt);
            }
        });

        lblScore.setText("Score : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnRep1)
                .addGap(18, 18, 18)
                .addComponent(btnRep4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSuivante)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRep3)
                        .addGap(28, 28, 28)
                        .addComponent(btnRep2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_Feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblScore)
                    .addComponent(lbl_Feedback))
                .addGap(33, 33, 33)
                .addComponent(lblQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRep4)
                    .addComponent(btnRep1)
                    .addComponent(btnRep3)
                    .addComponent(btnRep2))
                .addGap(37, 37, 37)
                .addComponent(btnSuivante)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep1ActionPerformed
        repondre(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRep1ActionPerformed

    private void btnRep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep2ActionPerformed
        repondre(2);
// TODO add your handling code here:
    }//GEN-LAST:event_btnRep2ActionPerformed

    private void btnRep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep3ActionPerformed
        repondre(3);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRep3ActionPerformed

    private void btnRep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep4ActionPerformed
    repondre(2);
// TODO add your handling code here:
    }//GEN-LAST:event_btnRep4ActionPerformed

    private void btnSuivanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivanteActionPerformed
        index++;

        if (index >= questions.length) {
            lblQuestion.setText("FIN DU QUIZ");
            lbl_Feedback.setText("Score final : " + score);
            btnSuivante.setEnabled(false);
         
        }else {
            afficherQuestion();
        }
    
    }//GEN-LAST:event_btnSuivanteActionPerformed
   
    
    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRep1;
    private javax.swing.JButton btnRep2;
    private javax.swing.JButton btnRep3;
    private javax.swing.JButton btnRep4;
    private javax.swing.JButton btnSuivante;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lbl_Feedback;
    // End of variables declaration//GEN-END:variables

}
