/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chevauchée_fantastique_valentini;

/**
 *
 * @author stell
 */
public class Acceuil extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Acceuil.class.getName());

    /**
     * Creates new form Acceuil
     */
    public Acceuil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_bienvenue = new javax.swing.JLabel();
        texte_explication_1 = new javax.swing.JLabel();
        texte_explication_2 = new javax.swing.JLabel();
        texte_explication_3 = new javax.swing.JLabel();
        texte_explication_4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_bienvenue.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        texte_bienvenue.setForeground(new java.awt.Color(255, 102, 102));
        texte_bienvenue.setText("Bienvenue dans Chevauchée Fantastique ! ");
        texte_bienvenue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(texte_bienvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        texte_explication_1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        texte_explication_1.setText("Partez à l’aventure avec votre cavalier sur un damier magique. ");
        getContentPane().add(texte_explication_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 670, 32));

        texte_explication_2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        texte_explication_2.setText("Votre objectif : éteindre toutes les cases allumées en respectant le mouvement du cavalier");
        getContentPane().add(texte_explication_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 1000, -1));

        texte_explication_3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        texte_explication_3.setText("sans jamais repasser sur une case déjà visitée !");
        getContentPane().add(texte_explication_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, -1, -1));

        texte_explication_4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        texte_explication_4.setText("Relevez les défis de chaque niveau et testez votre logique pour devenir un maître du parcours !");
        getContentPane().add(texte_explication_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("niveau 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 670, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("niveau 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 670, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("niveau 3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 670, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Jeu jeu = new Jeu(1); // niveau 1
    jeu.setVisible(true);
    this.dispose(); 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    Jeu jeu = new Jeu(2); // niveau 2
    jeu.setVisible(true);
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    Jeu jeu = new Jeu(3); // niveau 3
    jeu.setVisible(true);
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Acceuil().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel texte_bienvenue;
    private javax.swing.JLabel texte_explication_1;
    private javax.swing.JLabel texte_explication_2;
    private javax.swing.JLabel texte_explication_3;
    private javax.swing.JLabel texte_explication_4;
    // End of variables declaration//GEN-END:variables
}
