/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chevauchée_fantastique_valentini;

/**
 *
 * @author stell
 */
public class Jeu extends javax.swing.JFrame {
    
   
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Jeu.class.getName());

    /**
     * Creates new form Jeu
     */
    public Jeu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Case1 = new javax.swing.JButton();
        Case2 = new javax.swing.JButton();
        Case3 = new javax.swing.JButton();
        Case4 = new javax.swing.JButton();
        Case5 = new javax.swing.JButton();
        Case6 = new javax.swing.JButton();
        Case7 = new javax.swing.JButton();
        Case8 = new javax.swing.JButton();
        Case9 = new javax.swing.JButton();
        Case10 = new javax.swing.JButton();
        Case11 = new javax.swing.JButton();
        Case12 = new javax.swing.JButton();
        Case13 = new javax.swing.JButton();
        Case14 = new javax.swing.JButton();
        Case15 = new javax.swing.JButton();
        Case16 = new javax.swing.JButton();
        Case17 = new javax.swing.JButton();
        Case18 = new javax.swing.JButton();
        Case19 = new javax.swing.JButton();
        Case20 = new javax.swing.JButton();
        Case21 = new javax.swing.JButton();
        Case22 = new javax.swing.JButton();
        Case23 = new javax.swing.JButton();
        Case24 = new javax.swing.JButton();
        Case25 = new javax.swing.JButton();
        Case26 = new javax.swing.JButton();
        Case27 = new javax.swing.JButton();
        Case28 = new javax.swing.JButton();
        Case29 = new javax.swing.JButton();
        Case30 = new javax.swing.JButton();
        Case31 = new javax.swing.JButton();
        Case32 = new javax.swing.JButton();
        Case33 = new javax.swing.JButton();
        Case34 = new javax.swing.JButton();
        Case35 = new javax.swing.JButton();
        Case36 = new javax.swing.JButton();
        bouton_quitter = new javax.swing.JButton();
        bouton_recommencer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(7, 6));

        Case1.setText("jButton1");
        getContentPane().add(Case1);

        Case2.setText("jButton2");
        getContentPane().add(Case2);

        Case3.setText("jButton3");
        getContentPane().add(Case3);

        Case4.setText("jButton4");
        getContentPane().add(Case4);

        Case5.setText("jButton5");
        getContentPane().add(Case5);

        Case6.setText("jButton6");
        getContentPane().add(Case6);

        Case7.setText("jButton7");
        getContentPane().add(Case7);

        Case8.setText("jButton1");
        getContentPane().add(Case8);

        Case9.setText("jButton1");
        getContentPane().add(Case9);

        Case10.setText("jButton1");
        getContentPane().add(Case10);

        Case11.setText("jButton1");
        getContentPane().add(Case11);

        Case12.setText("jButton1");
        getContentPane().add(Case12);

        Case13.setText("jButton1");
        getContentPane().add(Case13);

        Case14.setText("jButton1");
        Case14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case14ActionPerformed(evt);
            }
        });
        getContentPane().add(Case14);

        Case15.setText("jButton1");
        getContentPane().add(Case15);

        Case16.setText("jButton1");
        getContentPane().add(Case16);

        Case17.setText("jButton1");
        getContentPane().add(Case17);

        Case18.setText("jButton1");
        getContentPane().add(Case18);

        Case19.setText("jButton1");
        getContentPane().add(Case19);

        Case20.setText("jButton1");
        Case20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case20ActionPerformed(evt);
            }
        });
        getContentPane().add(Case20);

        Case21.setText("jButton1");
        getContentPane().add(Case21);

        Case22.setText("jButton1");
        getContentPane().add(Case22);

        Case23.setText("jButton1");
        Case23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case23ActionPerformed(evt);
            }
        });
        getContentPane().add(Case23);

        Case24.setText("jButton1");
        getContentPane().add(Case24);

        Case25.setText("jButton1");
        Case25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case25ActionPerformed(evt);
            }
        });
        getContentPane().add(Case25);

        Case26.setText("jButton1");
        Case26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case26ActionPerformed(evt);
            }
        });
        getContentPane().add(Case26);

        Case27.setText("jButton1");
        getContentPane().add(Case27);

        Case28.setText("jButton1");
        getContentPane().add(Case28);

        Case29.setText("jButton1");
        getContentPane().add(Case29);

        Case30.setText("jButton1");
        getContentPane().add(Case30);

        Case31.setText("jButton1");
        getContentPane().add(Case31);

        Case32.setText("jButton1");
        Case32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Case32ActionPerformed(evt);
            }
        });
        getContentPane().add(Case32);

        Case33.setText("jButton1");
        getContentPane().add(Case33);

        Case34.setText("jButton1");
        getContentPane().add(Case34);

        Case35.setText("jButton1");
        getContentPane().add(Case35);

        Case36.setText("jButton1");
        getContentPane().add(Case36);

        bouton_quitter.setText("Quitter");
        getContentPane().add(bouton_quitter);

        bouton_recommencer.setText("Recommencer");
        bouton_recommencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_recommencerActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_recommencer);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouton_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_recommencerActionPerformed

    // TODO add your handling code here:
    }//GEN-LAST:event_bouton_recommencerActionPerformed

    private void Case14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Case14ActionPerformed

    private void Case20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Case20ActionPerformed

    private void Case23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Case23ActionPerformed

    private void Case25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Case25ActionPerformed

    private void Case26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Case26ActionPerformed

    private void Case32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Case32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Case32ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Jeu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Case1;
    private javax.swing.JButton Case10;
    private javax.swing.JButton Case11;
    private javax.swing.JButton Case12;
    private javax.swing.JButton Case13;
    private javax.swing.JButton Case14;
    private javax.swing.JButton Case15;
    private javax.swing.JButton Case16;
    private javax.swing.JButton Case17;
    private javax.swing.JButton Case18;
    private javax.swing.JButton Case19;
    private javax.swing.JButton Case2;
    private javax.swing.JButton Case20;
    private javax.swing.JButton Case21;
    private javax.swing.JButton Case22;
    private javax.swing.JButton Case23;
    private javax.swing.JButton Case24;
    private javax.swing.JButton Case25;
    private javax.swing.JButton Case26;
    private javax.swing.JButton Case27;
    private javax.swing.JButton Case28;
    private javax.swing.JButton Case29;
    private javax.swing.JButton Case3;
    private javax.swing.JButton Case30;
    private javax.swing.JButton Case31;
    private javax.swing.JButton Case32;
    private javax.swing.JButton Case33;
    private javax.swing.JButton Case34;
    private javax.swing.JButton Case35;
    private javax.swing.JButton Case36;
    private javax.swing.JButton Case4;
    private javax.swing.JButton Case5;
    private javax.swing.JButton Case6;
    private javax.swing.JButton Case7;
    private javax.swing.JButton Case8;
    private javax.swing.JButton Case9;
    private javax.swing.JButton bouton_quitter;
    private javax.swing.JButton bouton_recommencer;
    // End of variables declaration//GEN-END:variables
}
